security:
  firewalls:
    main:
      pattern:    ^/
      fr3d_ldap:  ~
      form_login:
          always_use_default_target_path: true
          default_target_path: /
      logout:     true
      anonymous:  true
    dev:
     pattern:  ^/(_(profiler|wdt)|css|images|js)/
     anonymous:  true

  providers:
    chain_provider:
      chain:
        providers: [fos_userbundle, fr3d_ldapbundle]

    fr3d_ldapbundle:
      id: fr3d_ldap.security.user.provider

    fos_userbundle:
      id: fos_user.user_provider.username

  encoders:
    Telus\Shared\TIUserBundle\Entity\User: plaintext

  access_control:
    - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
    - { path: ^/, roles: ROLE_USER }
    - { path: ^/reportes, roles: ROLE_REPORTES }
