Telus\Example\MyBundle\Entity\Sf2DataFormat:
    type: entity
    table: sf2_data_format
    uniqueConstraints:
        sf2_format_name:
            columns:
                - sf2_format_name
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            id: true
            generator:
                strategy: IDENTITY
    fields:
        sf2FormatName:
            type: string
            nullable: false
            length: 25
            fixed: false
            comment: ''
            column: sf2_format_name
        createdAt:
            type: datetime
            nullable: false
            comment: ''
            column: created_at
        updatedAt:
            type: datetime
            nullable: false
            comment: ''
            column: updated_at
        sf2FormatPrettyName:
            type: string
            nullable: false
            length: 25
            fixed: false
            comment: ''
            column: sf2_format_pretty_name
        sf2PbdEnabled:
            type: boolean
            nullable: false
            comment: ''
            column: sf2_pbd_enabled
    lifecycleCallbacks:
        prePersist: [ setCreatedAtValue, setUpdatedAtValue ]
        preUpdate: [ setUpdatedAtValue ]
