parameters:
#    ti_jarvis.example.class: Telus\Shared\TIJarvisBundle\Example

services:
#    ti_jarvis.example:
#        class: %ti_jarvis.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
